# Generated by Django 4.2.7 on 2023-12-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_customer_password_alter_collection_featured_product_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(default="password", max_length=50),
        ),
    ]
