# Generated by Django 4.2.7 on 2023-12-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_customer_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="password",
            field=models.CharField(max_length=50),
        ),
    ]
